build:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman -Syu --noconfirm
    - pacman -S buildah podman --noconfirm
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - buildah bud --pull -t "$CI_REGISTRY_IMAGE" .
    - buildah push "$CI_REGISTRY_IMAGE"
  only:
    - master
