variables:
  STORAGE_DRIVER: 'vfs'

build:
  image: quay.io/buildah/stable:latest
  stage: build
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - buildah bud --pull -t "$CI_REGISTRY_IMAGE" .
    - buildah push "$CI_REGISTRY_IMAGE"
  only:
    - master
